# Acknowledgments

We thank Cathy Jenks for editorial help, and Beate Helle for help with figure design. We thank and acknowledge all data contributors and data curators of the open accessible databases we have used. We dedicate this article to the memory of Eric C. Grimm (1951–2020), who was initially involved in the HOPE project. We express our deep gratitude for his long dedication and ground-breaking work in palaeoecological research, and his initiatives in developing the Neotoma Palaeoecology Database and Community.

## Funding

European Research Council Advanced Grant Humans on Planet Earth – Long-term impacts on biosphere dynamics (HOPE) awarded to HJBB (grant no. 741413) (HJBB, VAF, OM, SGAF, KPB, MJS, AWRS, HHB, JAG)

Trond Mohn Research Foundation (TMF) Startup Grant “Past, Present, and Future of Alpine Biomes Worldwide” (grant no. TMS2022STG03) (SGAF)

University of Bergen Startup Grant “Past, Present, and Future of Alpine Biomes Worldwide” (grant no. TMS2022STG03) (SGAF)

National Natural Science Foundation of China (grant no. 41988101) (XC, FC)

Australian Research Council’s Centre of Excellence for Australian Biodiversity and Heritage (CABAH) (AVH, SGH)

Czech Science Foundation PIF grant (GN23-06386I) (OM)

Charles University Research Centre program (UNCE/24/SCI/006) (OM)

Institutional Support for Science and Research of the Ministry of Education, Youth and Sports of the Czech Republic (OM)

Estonian Research Council (PRG874, PRG1993), Estonian Ministry of Education and Research, Centre of Excellence for Sustainable Land Use (TK232) (TR)

## Author contributions

Conceptualisation: HJBB

Funding acquisition: HJBB, SGAF, OM, SGH, TR, FC

Methodology – assembling and processing data: VAF, OM, SGAF, KPB

Methodology – providing fossil pollen data from Asia: XC, FC

Methodology – initial discussions and methodological development: HJBB, MJS, TR, AWRS, SN, HHB, JAG, CJFB, PŠ

Methodology – R code and workflow development: VAF, OM, SGAF, KPB

Methodology – process for human detection in Central & South America: OM, SGAF

Methodology – human-impact/presence indicators and pollen harmonisation for Central & South America: HH, SGAF

Methodology - providing data, pollen harmonisation, and detecting human-impact events for Oceania: SGH, AVH

Methodology – pollen harmonisation for Northern Hemisphere: HJBB; KPB

Methodology – detecting human-impact events for Northern Hemisphere: HJBB, HHB

Methodology – data analysis: OM, VAF

Methodology - providing code for implementing DCCA in R, and advice on data analysis and summarisation: CJFB, PŠ

Methodology - providing code, advice, and feedback on using the p3k<sup>14</sup>C radiocarbon database and the methodology to create summed probability densities: DB, JF, ER, JAH, EG, CL & LM

Visualisation: OM, VAF, SGAF

Interpretations - regional knowledge and feedback on interpretations: TG, JWW, SJG, WT

Writing – original draft: VAF, OM, SGAF, AWRS

Writing – review and editing: VAF, OM, SGAF, KPB, HHB, JAG, HH, SN, TR, AWRS, MJS, CJFB, TG, SJG, SGH, AVH, PŠ, WT, JWW, DB, JF, EG, JAH, CL, LM, ER, XC, FC, HJBB

## Competing interests

The authors declare no competing interests.

# Data and materials availability

The source data are deposited and available for download via Zenodo (DOI: 10.5281/zenodo.11369243; <https://doi.org/10.5281/zenodo.11369243>). See methods for data description. The data are under a CC BY-NC-ND licence, which requires approval from data owners before use. Please contact Xianyong Cao (<xcao@itpcas.ac.cn>) for use of the Asian fossil pollen data.

All R code and workflows to reproduce the data processing, filtering, data analyses, and figures are available for download via Zenodo (DOI: 10.5281/zenodo.12773214; <https://doi.org/10.5281/zenodo.12773214> )
