#' @title Cast one temporal lifecycle column
#' @description
#' Cast persisted lifecycle values to the type generated by the current model
#' configuration builder.
#' @param current_column Vector read from persisted lifecycle state.
#' @param candidate_column Prototype vector from the candidate configuration.
#' @return Current values cast to the candidate column type.
#' @examples
#' cast_temporal_config_column(
#'   current_column = as.Date("2026-01-01"),
#'   candidate_column = NA_character_
#' )
cast_temporal_config_column <- function(
  current_column,
  candidate_column
) {
  if (
    is.character(candidate_column)
  ) {
    res <-
      as.character(current_column)

    return(res)
  }

  if (
    is.integer(candidate_column)
  ) {
    res <-
      as.integer(current_column)

    return(res)
  }

  if (
    is.double(candidate_column)
  ) {
    res <-
      as.double(current_column)

    return(res)
  }

  if (
    is.logical(candidate_column)
  ) {
    res <-
      as.logical(current_column)

    return(res)
  }

  if (
    inherits(candidate_column, "Date")
  ) {
    res <-
      as.Date(current_column)

    return(res)
  }

  if (
    inherits(candidate_column, "POSIXct")
  ) {
    res <-
      as.POSIXct(current_column, tz = "UTC")

    return(res)
  }

  res_column <-
    vctrs::vec_cast(
      current_column,
      candidate_column
    )

  return(res_column)
}
