---
title: "Results_validation"

  output:
  word_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
    
date: "2023-09-07"




```{r load-package, include = FALSE }

library(tidyverse)
library(usethis)
library(targets)
library(here)
library(data.tree)
library(flextable)
library(webshot)
library(officer)
library(officedown) 

```

```{r global-options, include = FALSE }

# chuncks defaults
knitr::opts_chunk$set(
  echo       = FALSE,
  message    = FALSE,
  warning    = FALSE,
  fig.align = "center",
  flextable::set_flextable_defaults(
  font.family = "Arial", font.size = 9, 
  theme_fun = "theme_vanilla",
  big.mark=""),
  fig.path="figures/"
)

```


```{r setup, include = FALSE}


#----------------------------------------------------------#
#  Load functions -----
#----------------------------------------------------------#

# list R functions and source them
lapply(
  list.files(
    path = here::here("R/functions"), #have to use here::here(); does not work without it
    pattern = "*.R",
    recursive = TRUE,
    full.names = TRUE
  ),
  source
) %>%
  invisible()


#----------------------------------------------------------#
#  Authorise the user -----
#----------------------------------------------------------#

# Define directory for external storage for users
auth_tibble <-
  tibble::tribble(
    ~name, ~path,
    "ondrej", "C:/Users/ondre/My Drive/",
    "vfe032", "G:/My Drive/"
  )

data_storage_path <-
  auth_tibble %>%
  dplyr::filter(name == Sys.info()["user"]) %>%
  purrr::pluck("path")


external_storage_targets <-
  paste0(
    data_storage_path,
    "_targets_h1"
  )


# set colours 
palette_ecozones <- 
  c( Polar = "#009292", 
     Cold_Without_dry_season_Very_Cold_Summer = "#004949", 
     Cold_Without_dry_season_Cold_Summer = "#006ddb", 
     Cold_Dry_Winter = "#6db6ff",
     Cold_Dry_Summer = "#b6dbff",
     Cold_Without_dry_season_Warm_Summer = "#117733",
     Cold_Without_dry_season_Hot_Summer = "#999933", 
     Temperate_Without_dry_season = "#DDCC77",
     Temperate_Dry_Winter = "#b66dff",
     Temperate_Dry_Summer = "#ffff6d",
     Arid = "#924900",  
     Tropical =  "#920000"
     )


#human vs climate
palette_pred <- c(human = "#663333", 
                  climate = "#BBBBBB") 

```




```{r load data}

output_h1_spatial <-  targets::tar_read(output_hvar_spatial,
                                        store = paste0(
                                          data_storage_path,
                                          "_targets_h1"
                                        ))

data_meta <- targets::tar_read(data_meta,
                               store = paste0(
                                 data_storage_path,
                                 "_targets_h1"
                               ))

# split ecozones
data_meta <- data_meta %>%
  dplyr::mutate(
    sel_classification = dplyr::case_when(
      ecozone_koppen_15 == "Cold_Without_dry_season" ~ ecozone_koppen_30,
      ecozone_koppen_5 == "Cold" ~ ecozone_koppen_15,
      ecozone_koppen_5 == "Temperate" ~ ecozone_koppen_15,
      .default = ecozone_koppen_5
    )
  ) 

```

```{r add constraining scores}

# add constrained ecoystem scores with spds; NAs when empty
output_h1_spatial <- 
  output_h1_spatial %>%
  mutate(constrained_scores = purrr::map(data_merge,
                                         .f =  possibly(get_scores_constrained_spd,
                                                        otherwise = NA_real_)))
  

```


```{r combine data}

# combine with data_meta
data_input <- 
  output_h1_spatial %>%
  inner_join(data_meta %>% 
               dplyr::select(dataset_id, 
                             sel_classification, 
                             region), 
             by = "dataset_id")
  

```




```{r run mvpart}

regional_data  <- data_input %>%
  dplyr::select(dataset_id, 
                region, 
                sel_classification, 
                data_merge) %>%
  unnest(data_merge) %>%
  nest(data_merge = -c(region, sel_classification))




# mvpart validation analysis
set.seed(1221)
region_run1 <- regional_data %>%
  mutate(mvpart_run1 = purrr::map(data_merge,
                                  .f = ~run_mvpart(.,
                                                   preds = "age")))

set.seed(1222)
region_run2 <- regional_data %>%
  mutate(mvpart_run2 = purrr::map(data_merge,
                                  .f = ~run_mvpart(.,
                                                   preds = "spd")))
set.seed(1223)
region_run3 <- regional_data %>%
  mutate(mvpart_run3 = purrr::map(data_merge,
                                  .f = ~run_mvpart(.,
                                                   preds = "spd + age")))
set.seed(1224)
region_run4 <- regional_data %>%
  mutate(mvpart_run4 = purrr::map(data_merge,
                                  .f = ~run_mvpart(.,
                                                   preds = "spd + age + temp_annual + temp_cold + prec_summer + prec_win")))


  

```