## Extended Tables

::: {#exttbl-fossilpol-settings}
Selection of settings applied in our FOSSILPOL workflow [@methods-ref-51].
:::

| **Settings** | **Setting type** | **Selection** |
| --- | --- | --- |
| General |  |  |
|  | geography_criteria | -180 |
|  | long_max | 180 |
|  | lat_min | -90 |
|  | lat_max | 90 |
|  | alt_min |  |
|  | alt_max |  |
|  | private_data | TRUE |
| Neotoma |  |  |
|  | dataset_type | pollen |
|  | sel_var_element | pollen |
|  | chron_order.type1 | Varve years BP |
|  | chron_order.type2 | Calibrated radiocarbon years BP |
|  | chron_order.type3 | Calendar years BP |
|  | chron_order.type4 | Radiocarbon years BP |
|  | chron_order.type5 | Calendar years AD/BC |
|  | chron_order.type6 |  |
| Age-depth<br> models |  |  |
|  | min_n_of_control_points | 3 |
|  | default_thickness | TRUE |
|  | default_error | 100 |
|  | max_age_error | 3000 |
|  | guess_depth | 10 |
|  | default_iteration | 10000 |
|  | default_burn | 2000 |
|  | default_thin | 8 |
|  | iteration_multiplier | 5 |
| Site filtering |  |  |
|  | pollensum.filter_by_pollen_sum | TRUE |
|  | pollensum.min_n_grains | 25 |
|  | pollensum.target_n_grains | 150 |
|  | pollensum.percentage_samples | 50 |
|  | filter_by_age_limit | TRUE |
|  | extrapolation.filter_by_extrapolation | TRUE |
|  | extrapolation.maximum_age_extrapolation | 3000 |
|  | extrapolation.filter_by_interest_region | TRUE |
|  | extrapolation.n_levels.filter_by_number_of_levels | TRUE |
|  | extrapolation.n_levels.min_n_levels | 5 |
|  | extrapolation.use_age_quantiles | TRUE |
|  | extrapolation.use_bookend_level | TRUE |
| Data download: 23-05-2022 |  |  |

::: {#exttbl-human-events}
Type of human events identified in pollen sequences
:::

| **Region** | **Human-impact event type** | **Detection criteria** |
| --- | --- | --- |
| North America | BI = No Evidence of Impact |  |
| North America | FCu = First Cultivation | First unambiguous palynological evidence for cultivation of cereals (*Zea mays, Triticum, Aven*a, etc.) and other crop plants (e.g. *Cannabis sativa*). |
| North America | ES = European Settlement | First unambiguous indications of European settlement as shown in eastern and central US by a marked expansion of *Ambrosia*-type pollen, often accompanied by rises of Amaranthaceae undiff. (= *Chenopodium*-type), weeds such as *Plantago, Salsola kali*, and cultivated plants such as *Zea mays*, other cereals, and *Cannabis sativa*. In the Canadian prairie, the palynological evidence is often sustained rises of *Cyclachaena xanthifolia*-type (= *Iva xanthifolia*-type), *Salsola kali,* Amaranthaceae undiff., and *Iva ciliata*-type. In the Pacific North West, (e.g. western Washington, western Oregon, British Columbia, northern California), palynological evidence for European settlement in the mid-1800s consists of marked declines in coniferous tree pollen (e.g. *Pseudotsuga* (*menziesii*) *Thuja* (*plicata*), *Tsuga* (*heterophylla*), *Abies* (*grandis*), *Picea* (*sitchensis*), and sharp rises in pollen of *Alnus* (*rubra*) and *Populus* (*trichocarpa*). |
| Europe | BI = No Evidence of Impact |  |
| Europe | FI = First Indication | First unambiguous indications of human impact, as shown in northern and central Europe by the beginnings of a continuous curve for *Plantago lanceolata*-type pollen. In the Alps and southern Europe, the curves for *P. atrata*-type, *P. major*-type, and/or *P. maritima*-type pollen are, in the absence of *P. lanceolata*-type, good indicators as they contain species (e.g. *P. major, P. serpentina*) that have very similar ecologies to *P. lanceolata*. |
| Europe | FCu = First Cultivation | First unambiguous indicators of cultivation of cereals and, at some sites, *Cannabis sativa*. |
| Europe | EC = Extensive Clearance | Onset of extensive clearance (50%) of forest within the pollen-source area (PSA) of the sites. The criteria used involve a) a synthesis of work on the AP/NAP ratio; b) use of Poaceae % values (expressed as % total tree pollen) to define extensive clearance (ca. 50% of the PSA of the site being cleared of woodland); c) use of general pollen-representation factors to determine what Poaceae % values (expressed as % total pollen excluding spores and obligate aquatics) when transformed give an inferred value of 50% forestless landscape; and d) examination of pollen stratigraphies used in Sugita-type REVEALS reconstruction of past vegetation at the landscape-scale. We use 10% Poaceae or 10% *Calluna* pollen as the criterion for EC in this work. |
| Europe | CC = Complete Clearance | Onset of complete clearance of forest within the PSA. The decision of what criterion to use to recognise CC follows those used to derive values for the onset of extensive clearance. The criterion is 20% Poaceae or 20% *Calluna* pollen (expressed as % total pollen excluding spores and obligate aquatics). |
| Asia | BI = No Evidence of Impact |  |
| Asia | FI = First Indication | First unambiguous palynological indications of human impact as shown by statistically significant increases in Poaceae pollen, corresponding decreases in forest tree pollen, and the beginnings of scattered occurrences of, inter alia, *Plantago, Rumex*, Amaranthaceae, and Fabaceae pollen. In tropical sequences (e.g. Malayan Borneo), it is based on marked declines in pollen values of ‘primary’ forest trees and an increase in pollen of ‘secondary’ trees such as *Trema*. |
| Asia | FCu = First Cultivation | First unambiguous palynological evidence for cultivation of cereals and other crop plants (e.g. *Fagopyrum, Cannabis sativa, Juglans regia*). |
| Asia | EI = Extensive Impact | Unambiguous palynological evidence for ‘extensive impact’ in the Levant area as provided by massive deforestation and major changes in palynological composition. |
| Oceania | none = No Impact | No discernible evidence for human influence on vegetation change (note: In Oceania human interactions with vegetation has an antiquity of at least 50,000 years, however, this interaction is difficult to unequivocally detect in the pollen and charcoal records) |
| Oceania | weak = Weak Impact | Low impact on temperate vegetation is shown by minor increases in open vegetation (*Poaceae*), woodland disturbance (changes in dominance of fire-sensitive (e.g. *Callitris*, *Casuarina*) versus fire -adapted trees (including *Eucalyptus*), plus minor increases in fire events. In tropical sequences (e.g. Papua New Guinea), it is marked by minor declines in ‘primary’ forest pollen values of forest trees and minor increases in pollen of ‘secondary’ trees such as *Trema* and *Dodonaea*. |
| Oceania | medium = Medium Impact | Medium impact on temperate vegetation is shown by significant increases in open vegetation (*Poaceae*), woodland disturbance (e.g. prolonged declines in fire sensitive vegetation, such as long lived *Callitris*, *Casuarina*, and *Dicksonia* ferns, and an increase in fire-adapted vegetation including *Eucalyptus*), plus rapid changes in occurrence of fire events. In tropical sequences (e.g. Papua New Guinea), it is based on marked declines in ‘primary’ forest pollen values of forest trees and an increase in pollen of ‘secondary’ trees such as *Trema* and *Dodonaea*. |
| Oceania | strong = Strong Impact | Unambiguous palynological evidence for ‘strong impact’ is evidenced by a combination of massive deforestation due to clearance, by woody thickening the region due to the impact of colonisation, and a disruption of fire regimes reflected in variable fire responses. In temperate regions of Oceania (e.g. Australia) this is a result of forced cessation of Indigenous land management practices and use of fire to maintain once open landscapes at the time of colonisation around 300-240 years ago. The pollen sequences are characterised by major changes in palynological composition including introduction of weeds (e.g. *Pinus* and *Rumex*). In the tropics strong impact is evident in some sites with significant clearance of forests, increased *Poaceae* and the rise in Casuarina due to deliberate planting for horticultural purposes (occurs in Papua New Guinea montane sites after 2000 yr BP). |

::: {#exttbl-spd-climate}
Ratio of importance of past human presence (SPD) and palaeoclimate
:::

| Age ka BP | Predictor | North America | Central & South America | Europe | Asia | Oceania |
|:---------:|:---------:|:-------------:|:-----------------------:|:------:|:----:|:-------:|
|    500    |  climate  |     0.66      |          1.00           |  0.87  | 1.00 |  0.92   |
|    500    |   human   |     0.34      |          0.00           |  0.13  | 0.00 |  0.08   |
|   1000    |  climate  |     0.90      |          1.00           |  0.95  | 0.87 |  0.67   |
|   1000    |   human   |     0.10      |          0.00           |  0.05  | 0.13 |  0.33   |
|   1500    |  climate  |     0.93      |          0.89           |  0.98  | 0.94 |  0.68   |
|   1500    |   human   |     0.07      |          0.11           |  0.02  | 0.06 |  0.32   |
|   2000    |  climate  |     0.95      |          0.98           |  0.96  | 0.79 |  0.26   |
|   2000    |   human   |     0.05      |          0.02           |  0.04  | 0.21 |  0.74   |
|   2500    |  climate  |     0.92      |          0.96           |  0.95  | 0.94 |  0.78   |
|   2500    |   human   |     0.08      |          0.04           |  0.05  | 0.06 |  0.22   |
|   3000    |  climate  |     0.90      |          0.95           |  0.91  | 0.95 |  0.80   |
|   3000    |   human   |     0.10      |          0.05           |  0.09  | 0.05 |  0.20   |
|   3500    |  climate  |     0.96      |          0.93           |  0.72  | 0.94 |  0.85   |
|   3500    |   human   |     0.04      |          0.07           |  0.28  | 0.06 |  0.15   |
|   4000    |  climate  |     0.90      |          0.88           |  0.93  | 0.94 |  0.90   |
|   4000    |   human   |     0.10      |          0.12           |  0.07  | 0.06 |  0.10   |
|   4500    |  climate  |     0.91      |          0.92           |  0.97  | 0.83 |  0.96   |
|   4500    |   human   |     0.09      |          0.08           |  0.03  | 0.17 |  0.04   |
|   5000    |  climate  |     0.94      |          0.88           |  0.93  | 0.77 |  0.83   |
|   5000    |   human   |     0.06      |          0.12           |  0.07  | 0.23 |  0.17   |
|   5500    |  climate  |     0.88      |          0.95           |  0.99  | 0.93 |  0.92   |
|   5500    |   human   |     0.12      |          0.05           |  0.01  | 0.07 |  0.08   |
|   6000    |  climate  |     0.88      |          0.94           |  0.86  | 0.75 |  1.00   |
|   6000    |   human   |     0.12      |          0.06           |  0.14  | 0.25 |  0.00   |
|   6500    |  climate  |     0.91      |          1.00           |  0.66  | 0.95 |  1.00   |
|   6500    |   human   |     0.09      |          0.00           |  0.34  | 0.05 |  0.00   |
|   7000    |  climate  |     0.89      |          0.95           |  0.80  | 0.83 |  1.00   |
|   7000    |   human   |     0.11      |          0.05           |  0.20  | 0.17 |  0.00   |
|   7500    |  climate  |     0.89      |          0.96           |  0.54  | 0.86 |  1.00   |
|   7500    |   human   |     0.11      |          0.04           |  0.46  | 0.14 |  0.00   |
|   8000    |  climate  |     0.95      |          0.70           |  0.84  | 0.94 |  1.00   |
|   8000    |   human   |     0.05      |          0.30           |  0.16  | 0.06 |  0.00   |
|   8500    |  climate  |     0.96      |          0.93           |  0.89  | 0.97 |  1.00   |
|   8500    |   human   |     0.04      |          0.07           |  0.11  | 0.03 |  0.00   |

::: {#exttbl-events-climate}
Ratio of importance of human-impact events and palaeoclimate
:::

| Age ka BP | Predictor | North America | Central & South America | Europe | Asia | Oceania |
|:---------:|-----------|:-------------:|:-----------------------:|:------:|:----:|:-------:|
|    500    | climate   |     0.65      |          0.88           |  0.82  | 0.53 |  1.00   |
|    500    | human     |     0.35      |          0.12           |  0.18  | 0.47 |  0.00   |
|   1000    | climate   |     0.87      |          1.00           |  0.84  | 0.46 |  0.73   |
|   1000    | human     |     0.13      |          0.00           |  0.16  | 0.54 |  0.27   |
|   1500    | climate   |     0.94      |          0.99           |  0.82  | 0.40 |  1.00   |
|   1500    | human     |     0.06      |          0.01           |  0.18  | 0.60 |  0.00   |
|   2000    | climate   |     0.97      |          0.96           |  0.79  | 0.48 |  0.69   |
|   2000    | human     |     0.03      |          0.04           |  0.21  | 0.52 |  0.31   |
|   2500    | climate   |     0.94      |          0.88           |  0.85  | 0.61 |  0.84   |
|   2500    | human     |     0.06      |          0.12           |  0.15  | 0.39 |  0.16   |
|   3000    | climate   |     0.93      |          0.97           |  0.86  | 0.61 |  0.88   |
|   3000    | human     |     0.07      |          0.03           |  0.14  | 0.39 |  0.12   |
|   3500    | climate   |     0.92      |          0.89           |  0.63  | 0.90 |  1.00   |
|   3500    | human     |     0.08      |          0.11           |  0.37  | 0.10 |  0.00   |
|   4000    | climate   |     0.92      |          0.93           |  0.93  | 0.71 |  1.00   |
|   4000    | human     |     0.08      |          0.07           |  0.07  | 0.29 |  0.00   |
|   4500    | climate   |     0.93      |          0.94           |  0.95  | 0.82 |  *NA*   |
|   4500    | human     |     0.07      |          0.06           |  0.05  | 0.18 |  *NA*   |
|   5000    | climate   |     0.90      |          1.00           |  0.89  | 0.78 |  *NA*   |
|   5000    | human     |     0.10      |          0.00           |  0.11  | 0.22 |  *NA*   |
|   5500    | climate   |     0.90      |          1.00           |  0.97  | 0.88 |  *NA*   |
|   5500    | human     |     0.10      |          0.00           |  0.03  | 0.12 |  *NA*   |
|   6000    | climate   |     0.91      |          1.00           |  0.74  | 0.94 |  *NA*   |
|   6000    | human     |     0.09      |          0.00           |  0.26  | 0.06 |  *NA*   |
|   6500    | climate   |     0.91      |          0.98           |  0.97  | 0.98 |  *NA*   |
|   6500    | human     |     0.09      |          0.02           |  0.03  | 0.02 |  *NA*   |
|   7000    | climate   |     0.99      |          0.94           |  0.80  | 0.93 |  *NA*   |
|   7000    | human     |     0.01      |          0.06           |  0.20  | 0.07 |  *NA*   |
|   7500    | climate   |     0.86      |          0.98           |  0.75  | 0.95 |  *NA*   |
|   7500    | human     |     0.14      |          0.02           |  0.25  | 0.05 |  *NA*   |
|   8000    | climate   |     0.81      |          1.00           |  0.90  | 0.95 |  *NA*   |
|   8000    | human     |     0.19      |          0.00           |  0.10  | 0.05 |  *NA*   |
|   8500    | climate   |     0.71      |          1.00           |  0.95  | 0.93 |  *NA*   |
|   8500    | human     |     0.29      |          0.00           |  0.05  | 0.07 |  *NA*   |
