# Main Text

## Introduction

Human activity has transformed—and continues to transform—Earth's terrestrial ecosystems[@main-ref-01; @main-ref-02; @main-ref-03]. Over the last centuries, exponential growth in land-use intensity, economic growth, and consumption have had impacts on ecosystems in ways that are unprecedented in geological history[@main-ref-04; @main-ref-05; @main-ref-06]. Before the last few hundred years, archaeological and palaeoecological evidence shows that humans have inhabited much of Earth’s land for millennia, transforming natural landscapes into anthropogenic biomes through activities such as burning, deforestation, and cultivation[@main-ref-07], potentially even influencing global carbon cycling and climate change[@main-ref-08]. The extent of human impact has varied over time, driven by migrations, societal development, technological advancements, and increases in population densities, resulting in regionally distinct rates of vegetation transformation[@main-ref-01].

However, whilst the impacts of human activity on Earth’s ecosystems for the past few centuries are well established, the extent and magnitude of this human impact during earlier periods, particularly on vegetation composition and associated ecological processes, remains under exploration[@main-ref-09]. Lyons et al.[@main-ref-10] presented evidence that human activity was so pervasive that underlying ecological characteristics of communities were modified in the middle Holocene (~6 ka BP), arguing that dominant patterns in taxon co-occurrence patterns shifted from facilitative to competitive interactions as a result of human activity (although see the replies by Bertelsmeier & Ollier[@main-ref-11] and Telford et al.[@main-ref-12]). Mottl et al.[@main-ref-13] reported evidence of consistent increases in rates-of-change in pollen assemblages at continental scales since as early as 4.6 ka BP, likely the result of increased human activity and land-use change, although no attribution studies were carried out to confirm this assumption. Recent syntheses of palaeoecological and archaeological evidence have suggested that humans have likely shaped most of nature over the last 12 ka BP (i.e. Holocene), but evidence indicates that this human impact has occurred at different extents and intensities across continental regions[@main-ref-07; @main-ref-14; @main-ref-15; @main-ref-16]. Thus, detection and attribution of ecological changes in relation to human activity in the Holocene remains an important area of research if we are to understand the legacy of past drivers of change on shaping present-day ecosystem patterns.

A number of processes can influence the structure and composition of an ecological community at a given point in time[@main-ref-17]. For example, in addition to land-use change and disturbance related to human activity, climate also plays a major role in structuring vegetation communities, particularly on centennial to millennial timescales[@main-ref-18; @main-ref-19; @main-ref-20; @main-ref-21]. Environmental proxies from ice cores and deep-sea records have confirmed that climate fluctuations during the Pleistocene and the Holocene periods correspond with vegetation dynamics at regional and continental scales[@main-ref-22]. However, the relative roles of climate and human activity in shaping the structure and function of ecosystems, particularly at larger scales (e.g. regional to continental) within the Holocene period, remains poorly understood. At present, there has been no systematic attempt to disentangle the relative strength of these two drivers during such a critical period of Earth system transformation.

Here, we assembled a global dataset based on fossil pollen data, archaeological remains, and past climate variability (see **Methods**) to investigate the effects of both climate and human activity on vegetation assemblage dynamics —as inferred from pollen assemblages—in the Holocene. We standardised 1262 fossil pollen sequences from North America, Central and South America, Europe, Asia, and Oceania (@fig-conceptual-workflow; @extfig-data-coverage) and converted them into nine metrics, each of which reflect different properties of past vegetation assemblage change, including composition, diversity and rates-of-change (@tbl-pap-metrics). Since these are derived from pollen assemblages, we stress that these are indirect representations of vegetation assemblage change, hereafter defined as pollen assemblage properties[@main-ref-23] (PAPs, see **Methods**).

We then combined our fossil pollen data with archaeological evidence of past human activity based on two sources: (i) summed probability density (SPD) from over 150,000 archaeological radiocarbon dates[@main-ref-24], a validated proxy that goes beyond mere presence-absence indicators by reflecting the intensity and frequency of human activities in a given region[@main-ref-25; @main-ref-26] (See **Methods**), and (ii) a series of “human-impact events”, derived from expert-based detection of patterns of anthropogenic indicator taxa in pollen diagrams (@extfig-human-data-coverage, **Methods**). Note that we chose to focus on period between 8.5 – 2 ka BP, since there is a lack of radiocarbon datasets for the last two millennia in Europe and Asia[@main-ref-24] (@tbl-regional-summary). Finally, we used the *CHELSA-TraCE21k Paleoclimate database*[@main-ref-27] to extract climate predictors related to summer and winter precipitation, mean annual temperature, and minimum temperature of the coldest month.

We used this data compilation to test two hypotheses. The first hypothesis (H1) proposes that human impact was the primary driver of changes in PAPs at continental and subcontinental scales between 8.5 and 2 ka BP. We assessed the relative importance of human impact compared to climate, both spatially (by comparing fossil pollen sequences within climate zones and continents) and temporally (by examining trends across time slices). If human impact is an important driver of change in past patterns in PAPs, we expect its importance to match or exceed the importance of climate across both spatial and temporal dimensions. The second hypothesis (H2) proposes that human impact significantly altered the relationships among the different PAPs within these regions during the same time-period. If human impact was pervasive in the Holocene, we expect that they altered the covariance between the PAPs within different climate zones on continental regions.

## Results

### H1: Holocene human impact secondary to palaeoclimate

We used hierarchical variation partitioning (HVARPART) within a redundancy analysis (RDA)[@main-ref-28] to assess how each predictor—human activities and palaeoclimate—contributes to changes observed in the PAPs, in individual sequences (i.e. @fig-conceptual-workflow, @extfig-site-examples). We find that palaeoclimate has substantially greater importance than past humans in shaping the patterns of PAPs at continental and subcontinental scales (@fig-predictor-importance-spatial). Our spatial analysis shows high variation in the ratios of predictor importance of past humans and palaeoclimate across the middle to late Holocene (@fig-predictor-importance-spatial). While both have influenced the patterns in the vegetation metrics at individual sequences—with ratios of importance ranging between 0 and 1—the relative importance of climate increases with spatial scale. For example, at the climate-zone level, weighted mean ratios range from 0–0.71 for humans and 0.29–1 for palaeoclimate. At continental scales, these ratios are 0.15–0.32 for humans and 0.68–0.85 for palaeoclimate. Although palaeoclimate dominates, the impact of past humans is more pronounced in certain climate zones (not in the Polar and Cold climate zones) than its mean importance across all continents. Findings from Oceania, based on fewer than five sequences, lack robustness and should be interpreted with caution.

In addition to assessing the overall contribution of human impact and climate to the patterns in PAPs, we conducted a temporal analysis using both the summed probability densities (SPD) or human-impact events as predictors, to investigate how the importance of these two variables changed over time. Here, we find that palaeoclimate consistently emerges as the predominant factor influencing temporal variations in the spatial patterns of the PAPs across continents (@fig-predictor-importance-temporal). Trends are generally consistent among the different regions, though some exceptions exist. In Asia, the importance of humans as indicated by SPD is probably underestimated due to limited radiocarbon dates after 3.5 ka BP, whereas the human-impact events delimited by experts indicate increasing human influence. In Europe, the influence of humans is similarly underestimated after 3 ka BP, although the level of influence estimated by the human-impact events remains relatively stable after this time (@fig-predictor-importance-temporal). The weighted mean ratios comparing the influence of human population (SPD) and human-impact events to palaeoclimate are presented in @exttbl-spd-climate and @exttbl-events-climate.

### H2: Assessing the predictor importance for changes in interrelationships between PAPs

Our second hypothesis explores the stability of relationships among PAPs, over time. Specifically, we aim to determine whether changes in these relationships can be attributed to human activity or climate changes, thereby assessing the drivers behind the observed ecological dynamics. We used principal component analysis (PCA) and symmetrical Procrustes sum-of squares (*m*<sup>2</sup>) to quantify the change in covariance among the PAPs between each pair of time slices within the climate zones[@main-ref-29] (**Methods**). This results in pairwise *m*<sup>2</sup> distance matrices that are subsequently used as response variables in a second hierarchical variation partitioning (HVARPART) analysis (**Methods**). Mean trends of humans and climate within different continental climate zones, derived by hierarchical generalised additive modelling (HGAM)[@main-ref-30] are integrated as predictors ([@extfig-spd-trajectories; @extfig-annual-temperature; @extfig-coldest-month-temperature; @extfig-warmest-quarter-precipitation; @extfig-coldest-quarter-precipitation]). The results are summarised in @fig-pap-interrelationships, which show how relationships between our different PAPs evolve over time, stratified by climate zones and continents. Starting at 8.5 ka BP, one can trace the evolving relationship between PAPs for a given climate zone by assessing how its trajectory moves through the ordination space in two dimensions. A stable relationship results in a trajectory spanning regions of the ordination space closer to the origin, while trajectories that span a larger area of ordination space indicate larger directional changes in the interrelationships among one or several metrics. The direction of the arrows illustrates how temporal changes in the interrelationships among PAPs correlate with human or climatic influences, whilst the length represents the strength of these influences, with longer arrows signifying greater correlations.

Based on this analysis, we find notable differences in the importance of humans as predictor for these changes in different continents, represented by the ratios of importance bars (@fig-pap-interrelationships), but observe that palaeoclimate plays a stronger role in most climate zones. Notably, the coldest regions, particularly Europe and North America's Polar, Cold, and Temperate without dry season zones, show considerably less change in the interrelationships of PAPs compared to other climate zones. This may suggest a climatic filtering effect on the PAPs, with underlying ecological processes either remaining unchanged or changing synchronously throughout the investigated period. In contrast, regions with higher environmental variation—in Cold, Temperate, Tropical, and Arid zones—show more dynamic change (i.e. time trajectories spanning larger areas of the ordination space and evolving in different directions), mainly caused by climatic variability, but also influenced in some regions by varying degrees of past human impact. Interestingly, this analysis demonstrates that past human activities correlate with different climate variables across various climate zones, as evidenced in @fig-pap-interrelationships. Predictor variables that point in the same direction along the gradient indicate positive correlations. We observe that the arrows representing climate variables often point in directions that are distinct from those representing the human predictor, and there are no clear patterns between the different climate zones and continents.

## Discussion

Our study used palaeoecological, archaeological, and palaeoclimate data to investigate two hypotheses about the Holocene extent of human impact on past vegetation assemblage dynamics (8.5 and 2 ka BP.). Our first hypothesis proposed that human impact was the primary driver of changes in PAPs, at continental and subcontinental scales between 8.5 and 2 ka BP. Our second hypothesis proposed that the interrelationships between these PAPs were affected by human activity between 8.5 and 2 ka BP. However, while our data show that it is likely that past humans have acted as strong disturbance factors at specific sites affecting establishment, abundance, and succession of past taxon populations, their overall importance is considerably lower than that of palaeoclimate changes. We also find that the influence of human activity consistently increases with decreasing spatial scale. Taken together, we refute both hypotheses and suggest that human impact was not a significant factor in driving vegetation assemblage dynamics at continental to global scales in the study period.

This finding contrasts with a number of previous studies that have identified evidence of humans dominating vegetation and land-use change in the Holocene[@main-ref-15; @main-ref-31; @main-ref-32; @main-ref-33; @main-ref-34]. One possible explanation is that, in our studied time window, prehistoric human populations were likely small and local, and therefore regional pollen rain masks any small local effects on vegetation in the landscape. Thus, although humans were most likely present across all regions, population densities and land-use type and intensity varied spatially[@main-ref-01], and so the timing and extent of human-impact events also varied considerably between individual sites. As a result, these local human impacts were less significant than any abiotic filtering reflected by climate, which remained the most important predictor in our analysis at continental to global scales.

We also note that, whilst other studies have focussed on land-use changes based on reconstructions of either landcover or anthropogenic biomes[@main-ref-32; @main-ref-35], our study goes beyond previous reconstructions of land-use by using PAPs. These PAPS reflect a broader set of vegetation assemblage processes (@tbl-pap-metrics) and may not necessarily be correlated with land-use change typically inferred from pollen assemblage composition (e.g. changes in composition do not necessarily imply alterations in species richness). Furthermore, whilst a number of studies have assessed variations in individual PAPs across regions[e.g. @main-ref-14; @main-ref-23; @main-ref-31; @main-ref-36], ours is the first to provide a more holistic perspective, using a multivariate framework to analyse all nine metrics of past vegetation assemblage changes and their interrelationships influenced by humans and climate simultaneously. Such multivariate analyses of PAPs represent a new approach in palaeoecology and more research is needed to understand how variations in these different assemblage properties are influenced by different types of human land-use and other factors.

We emphasise that our findings do not negate the effects of human activity in the Holocene. For example, our analysis indicates that whilst high impact-events, such as total forest clearance, do not show a consistently increasing pattern across regions, certain subcontinental regions do show a consistent increase in the extent of human impact during the period investigated, particularly the first impact of anthropogenic activity and the start of agriculture (@extfig-human-events). Similarly, whilst our results did indicate that human impact on PAPs at continental scales is more pronounced after ~5 ka BP, this influence was neither spatially coherent nor consistent. For example, human importance surpassing palaeoclimate is observed in Asia (human-impact events) and Oceania (human-impact events and SPD) at 2.5 ka BP and 2.0 ka BP, respectively (@fig-predictor-importance-temporal). In contrast, for many other regions (e.g. North America, Central and South America, and Europe), palaeoclimate remains the dominant driver in PAPs throughout the Holocene, despite increasing human importance after ~2.0, 1.0, or 3.5 ka BP, respectively. Thus, our results indicate that the site-specific effect of human impact should not be generalised to a continental or global scale and emphasise the importance of climate in shaping the underlying characteristics of the ecological assemblages in the study period.

Such results have several implications for understanding the long-term interactions of humans and of both past and present ecosystems. First, a number of studies have argued that Holocene human impacts on vegetation assemblages were extensive, potentially even affecting the general rules that govern the formation of biotic assemblages through time[@main-ref-10]. If this was the case, then we would expect differences in both the drivers of the patterns in PAPs (H1) and their associations (H2). Our results do not reveal such differences. While we cannot reject the evidence of human impact locally, we emphasise that at, larger scales, climate has remained a dominant predictor of the patterns in our PAPs between 8.5 and 2 ka BP, and any human impacts that did occur were not large enough to result in widespread and universal ecosystem change. Such findings also support the idea that, whilst human impact during the mid Holocene was present in some regions, the effects of human impact are not uniform and so context dependency remains essential for understanding present-day ecosystems.

Second, our findings align with recent global assessments[@main-ref-14] and may help to explain the absence of coherent tipping points in terrestrial ecosystems. The high heterogeneity among regions, with the spatially variable influence of climatic factors and the interactions among taxa, contributes to highly variable assemblage dynamics both temporally and spatially. Such heterogeneity complicates the detection and quantification of overarching trends at a continental or global scale, as it tends to obscure any consistent patterns.

Third, we caution against a prevailing narrative that human transformation of the terrestrial biosphere is always destructive[@main-ref-07]. Our results are in line with other recent studies that human impact has been present in the Holocene, but interestingly, our results support the idea that the effects of preindustrial societies on vegetation assemblage dynamics were less influential than other drivers at continental to global scales[@main-ref-37; @main-ref-38; @main-ref-39]. Numerous studies have highlighted the positive effects of human land-use through indigenous knowledge relating to sustainable land-management[@main-ref-09; @main-ref-40; @main-ref-41; @main-ref-42]. Although it is evident that some societies have caused substantial ecosystem changes and even local extinctions in the past, our results indicate that climate was the primary driver of underlying ecological processes at regional to continental scales during these times.

Fourth, whilst our results refute both hypotheses about the direct impacts of human activity on PAPs in comparison to climate, our analysis cannot refute the possibility that climate indirectly influenced ecological processes via human impact, such as the effects on harvest yields, carrying capacities, and consequently, population densities[@main-ref-43]. This complexity makes it challenging to separate the impacts of human activities from those of climate. For instance, in analyses that do not account for feedback loops between humans and vegetation, such as the feedbacks among drought, fire and human activity, all change might be attributed to climate, even though human impact, such as fire management or grazing, could be equally influential if they are closely coupled to climate change[@main-ref-44]. Our second analysis show correlations between humans and climate in different climate zones. These results may argue for a third hypothesis that human activity, particularly farming, was co-shaped by climatic change[@main-ref-45]. These findings underscore the need for further research to fully understand these complex interdependencies.

Note that because of data limitations, our study focuses on the period between 8.5 and 2 ka BP. At present, the lack of availability of <sup>14</sup>C dating for the last 2 millennia makes human population density reconstructions unreliable, but there is widespread evidence of human impact from other sources from this period[@main-ref-46; @main-ref-47]. For example, Mottl et al. found continental scale increases in rates-of-change starting between 4.6 and 2 ka BP in different regions, with largest effects in the more recent times. Thus, whilst the impacts of human activity are limited in comparison with climate in our study period, we cannot evaluate the effects of preindustrial societies in the most recent millennia. In some regions, the significance of these effects may be heightened by evolving social cultures and complexities during specific archaeological periods[@main-ref-07; @main-ref-47]. These are historically documented periods of human introduction of many new plants to different continents[@main-ref-48], which has been linked to increases in pollen richness estimates and compositional changes[@main-ref-31]. At present, there remains a crucial gap that needs to be bridged between localized effects identified in prehistoric land-use and the larger scale transformations since 1950, related to the Great Acceleration[@main-ref-49].

Similarly, the climate model data that we use are generally appropriate for characterising mean changes. However, there may be mismatches between these data and pollen data, which are often collected from sequences near ecotone transitions to investigate past environmental changes. Such mismatches can arise because the climate models represent broader regional conditions that may not align perfectly with the specific localities from which pollen data are gathered. Additionally, inherent biases of pollen data, such as varying taxonomic resolution and the relative abundances of pollen types influenced by pollen production and dispersal properties, can also mask changes in the PAPs. These biases are further complicated by factors like vegetation density and structure, affecting the likelihood of pollen reaching a site[@main-ref-50]. To mitigate these issues, our data processing efforts have been designed to reduce the effect of varying taxonomical resolution, different sizes of pollen sums, and unevenly spaced temporal data points. This processing ensured that the inherent biases in the pollen data are more systematic within subcontinental regions, yielding a similar bias across sequences within the climate zones.

## Conclusion

The integration of 1262 fossil pollen sequences, archaeological radiocarbon dates, and palaeoclimate data into a large database has allowed us to examine the relative influences of human activity and palaeoclimate on pollen assemblage properties, from 8.5-2.0 ka BP at the global scale. At global to sub-continental scales, our results show that regional climate variability was more important than human activity in driving major vegetation assemblage patterns. Our results caution against extrapolating localised, intense human impacts to broader spatial scales, as we do not find evidence that these reflect widespread or global trends. Our study reinforces the essential role of interdisciplinary research in disentangling the confounding effects of human and climatic influences on past ecosystems.
