# Methods

We created a GitHub repository to host all R scripts and custom-made functions to process data and generate outputs for this project, ensuring full transparency and reproducibility (https://github.com/HOPE-UIB-BIO/PastHumanImpact). Additionally, all data, under specific licences, have been uploaded to ZENODO. Specific links are provided under **Data availability**. Our full workflow encompasses all steps from data input to the final outputs, including pollen sourcing and processing, calculations of pollen assemblage properties (PAPs), and statistical analyses.

## FOSSILPOL Workflow

Raw pollen datasets were curated using the R-Fossilpol package, following the guidelines in Flantua et al.[@methods-ref-51] and detailed on the FOSSILPOL project website[@methods-ref-52; @methods-ref-53]. The majority of data sequences were sourced from the *Neotoma Paleoecology Database*[@methods-ref-54], with additional data from private sources used to address regional gaps, particularly Asia. These additional datasets were accessed under CC BY-NC-ND 4.0 licence[@main-ref-23]. @exttbl-fossilpol-settings provides an overview of the parameters employed in the FOSSILPOL workflow for compiling and processing of pollen sequences. This workflow was refined during subsequent data-processing stages, yielding a high-quality compilation of pollen sequences suitable for numerical analyses and calculations of PAPs.

### Harmonisation tables

A key step in the FOSSILPOL workflow is the taxonomic and nomenclatural standardisation of pollen types to ensure dataset consistency both within and across regions. Variation in identification criteria and nomenclature among analysts from diverse backgrounds and schools may result in substantial discrepancies in pollen taxonomic levels and naming conventions, which would bias numerical comparison[@methods-ref-51]. To mitigate these biases, we developed harmonisation tables all regions included in this study, encompassing Europe, Levant, Siberia, Southern Asia, Northern America, Central and South America, and the Indo-Pacific region. These harmonisation tables[@main-ref-23; @methods-ref-55], were incorporated into the FOSSILPOL workflow.

### Data filtering

To ensure the highest possible data quality and facilitate numerical comparisons across multiple pollen sequences, several filtering criteria were carefully chosen and applied:

- Removal of potentially duplicated pollen sequences.

- Sorting assemblages (samples) by chronological order (age).

- Exclusion of assemblages (samples) with a total pollen count below a specified threshold (see below).

- Exclusion of pollen sequences falling outside defined age ranges.

- Exclusion of assemblages (samples) based on the age of the last control point.

- Exclusion of assemblages (samples) beyond the specified age ranges of interest.

- Exclusion of pollen sequences if the total number of samples was fewer than 5.

These filtering procedures were systematically applied to the chronologies, raw pollen counts, harmonised pollen counts, and age uncertainties derived from the age-depth models (Bchron)[@methods-ref-56; @methods-ref-57]. While the preferred minimum number of pollen grains was initially set at 150, this threshold resulted in a significant loss of pollen sequences, particularly in regions with limited data coverage. To balance data retention and quality the threshold was adjusted to 25, with the condition that less than 50% of the samples would have a low pollen sum. However, it should be noted that in such cases, the estimates of properties of pollen assemblages may exhibit reduced robustness. Regrettably, we excluded Africa as a region from our analysis because at the start of our project (2018) the coverage of pollen sequences available was too sparse. See data summaries in @extfig-data-coverage. A complete description of all filtering criteria used in the FOSSILPOL workflow is provided in @exttbl-fossilpol-settings.

## Estimating Metrics of Pollen Assemblage Properties (PAPs)

We calculated different metrics, derived from community ecology and biodiversity analyses, that reflect different properties of a pollen assemblage[e.g. @main-ref-23] for each pollen sequence in our dataset compilation. These are considered proxies for changes in different components of a vegetation assemblage over time. We note that although there is not a direct relationship between a pollen assemblage and the vegetation assemblage it might represent, the association between these two concepts is fundamental to palaeoecological research[@methods-ref-58]. We used a suite of metrics that represents palynological richness, diversity, evenness, compositional change and turnover, and rate-of-change (RoC). These metrics reflect components of an ecological assemblage, caused by underlying ecological processes and interactions between past species populations and environment, which may result in taxon gains or losses (richness), changes in abundances (evenness), change in both richness and evenness (diversity), and functioning and structure of assemblages (composition), and how a pollen assemblage changes over time and space (turnover and rate-of-change).

We calculated most metrics using the newly developed *R-Ecopol* package[@methods-ref-59]. The base functions used in this package are derived from other packages. Examples are *mvpart*[@methods-ref-60] to derive pollen zonations with multivariate regression trees, and *vegan*[@methods-ref-61] for other multivariate techniques and dissimilarity indices.

### Pollen richness, diversity, and evenness

Palynological richness, diversity, and evenness were estimated using Hill´s effective species numbers N0, N1, and N2, and the associated evenness ratios of N2/N1 and N1/N0[@methods-ref-58; @methods-ref-63]. The effective species numbers mainly differ in how rare taxa are weighted in comparison to abundant taxa depending on the parameter q in the formula[@methods-ref-58]:

$$
D^{q} = {(\sum_{i = 1}^{T}p_{i}^{q})}^{1/(1 - q)}
$$

where *D* is the diversity estimate, and *p* is the proportion of taxon *T<sub>i</sub>*. When *q* is 0, rare and abundant taxa have equal weight, and the number is simply the number of taxa in the sample. The equation is not defined for *q* = 1, but when it approaches 1, it equals the exponential of the well-known Shannon index and provides the number of equally common taxa. When *q* = 2, it is the same as the inverse Simpson diversity index and is the number of abundant taxa. Rare taxa receive a low weight. The advantage of using effective species numbers is that they provide easily interpretable units and contain the doubling effect[@methods-ref-63]. To standardise pollen sample sizes, we used the rarefaction approach developed by Chao et al.[@methods-ref-63]. These estimates were rarefied to the number of n = 150 grains, or in a few cases to a lower sum (minimum n = 25). Some pollen sequences from Asia were only available as pollen percentages; these are rarefied to the minimum sum of the percentages. The ratios (e.g. N2/N1) between any diversity numbers will be 1 if all taxa in a sample are equally abundant, hence these ratios reflect changes in evenness between rare, equally common, and abundant taxa.

Functions from *iNext*[@methods-ref-62; @methods-ref-63; @methods-ref-60] were modified to extract interpolated Hill numbers based on a minimum sample size and incorporated into *R-Ecopol* package[@methods-ref-59].

Despite our efforts to standardise richness and diversity estimates based on a standard sample size, there remain unaccountable biases, which include variations in total pollen production and pollen representation[@main-ref-50; @methods-ref-65].

### Compositional turnover

We estimated the compositional turnover using detrended canonical correspondence analysis (DCCA) with age as the explanatory variable[@methods-ref-64]. Changes in weighted average (WA) scores (*CaseR* scores) are measures of compositional turnover in standard deviation (SD) units[@methods-ref-66]. The WA scores were regressed with time using a second-order polynomial (age+age^2) to allow more flexibility in the turnover pattern within a pollen sequence. The total range of *CaseR* scores along DCCA axis 1 is a measure of total compositional change for a sequence, whereas the pattern of individual *CaseR* scores along DCCA axis 1 is a measure of turnover between individual samples within the sequence[@methods-ref-63]. The response data are pollen percentages without any transformation to maintain the chi-square distances between samples that is implicit in DCCA, whereas the ages are the median ages derived from the age-depth model for each sequence. We specifically developed R functions in the *R-Ecopol* package to run DCCA using *Canoco* 4.5[@methods-ref-64].

### Rate-of-change

To quantify the rate-of-change (RoC) of composition, we used the *R-Ratepol* package[@methods-ref-67]. RoC was calculated using moving windows of 500-year time bins, with five shifts for each bin where samples were randomly selected. This approach, as demonstrated by Mottl et al.[@methods-ref-67], enhances the accurate identification of RoC peak points compared to more traditional methods. The RoC values are reported as dissimilarity per 500 years, employing the chord dissimilarity coefficient[@methods-ref-68]. Standardisation of sample size was performed within each working unit, ensuring consistency at 150 grains or the lowest number detected in each dataset.

### Change-point detection and density estimations

For the calculation of change points in all the PAPs, we used conventional regression trees (RT) for single variables with Euclidean distances. An algorithm was developed to identify transitions between resulting groups or zones per variable by coding these transitions as binary variables (0/1). A change point was designated as 1, with the mean ages between two consecutive samples representing the timing of this significant change, determined individually for each pollen-assemblage property.

Compositional change was calculated using multivariate regression trees (MRT) with age as the sole constraining variable. MRT is, in general, a robust tool to explore and predict changes in multivariate datasets using external predictor variables[@methods-ref-68; @methods-ref-69]. This technique has been adopted in palaeoecology to detect zones in pollen diagrams or shifts between periods of homogeneous assemblages in time[@methods-ref-68]. We used the pollen taxa in percentages without any data transformations as the response variable and the median ages derived from the age-depth model as the constraining variable. The recursive partitioning is based on chi-square distances[@methods-ref-70] between pollen samples constrained by time. The number of cross-validations was set to 1000, and the optimal sized tree was chosen based on the 1SD rule[@methods-ref-68].

Significant change points for richness, diversity, and evenness variables were integrated into one variable (DDC), while significant change points for compositional turnover, compositional change, and rate-of-change were combined into a second variable (DCC). The density of these two variables was computed using a Gaussian kernel and rescaled to specific age ranges for each individual pollen sequence, including minimum and maximum ages. To address boundary concerns in density estimation, the data were reflected to 0.

## Equal temporal spacing of samples

We ensured equal temporal spacing of samples across all response variables, as this is crucial for temporal analyses in our stated hypotheses 1 and 2. This involves standardising samples to intervals of 500 years across time and space. Three methods of interpolation were tested: generalised additive model (GAM), hierarchical generalised additive model (HGAM), and simple linear interpolation. Linear interpolation was ultimately chosen as the preferred method, as it maintained the correlation structure between multivariate response variables closest to the original estimates, compared to GAM or HGAM. The latter models occasionally exhibited unexpected patterns in single pollen diversity estimates, which affected these correlations. Given the impracticality of individually assessing each model for every variable across all sequences (numbering over 1000), we opted for linear interpolation as the simplest approach.

After all data-processing steps, a total of 1262 sequences were available for analyses. For an overview of data coverage, see @extfig-data-coverage.

## Spatial units for analysis

The analyses focused on three levels of spatial units: 1) individual sequences, 2) sub-regions within continents, and 3) continental regions. While we acknowledge that any grouping will be imperfect and some specific regions might be less well represented, we used present-day Köppen-Geiger climate zones[@methods-ref-71] as a classification at the subcontinental scale. The advantage of using the Koppen-Geiger climate zones lies in its reliance solely on climate data, without making assumptions about vegetation or human influence. Additionally, these climate zones are characterized by relatively stable climates within each zone, enhancing the detectability of potential human impacts.

We used five major climate zones, namely Polar, Cold, Temperate, Arid, and Tropical for visualisation, but since the Cold and Temperate zones are so widespread across the Northern Hemisphere, we sub-divided these into Cold without Dry Season & Very Cold Summer, Cold without Dry Season & Cold Summer, Cold Dry Winter, Cold Dry Summer, Cold without Dry Season & Warm Summer, Cold without Dry Season & Hot Summer, Temperate without Dry Season, Temperate Dry Winter, and Temperate Dry Summer. This resulted in 12 climate zones used in the analyses.

## Detection of past human activities

To assess the historical influence of past human activities on past vegetation (i.e., pollen-assemblages), we created two proxies of past human presence for each sequence: (1) summed probability densities (SPDs)[@main-ref-24] of archaeological radiocarbon (<sup>14</sup>C) dates to quantify past human population and their regional dynamics, and (2) human events derived from fossil pollen diagrams based on expert knowledge. We used both proxies to assess the importance of past human presence and impact across regions and continents (@extfig-human-data-coverage). Such integration also helped to mitigate the potential issue of circularity wherein human events detected from the same pollen sequences are used to estimate ecological attributes of the pollen assemblages.

### Past human presence from archaeological radiocarbon dates

We used a global dataset of archaeological radiocarbon (<sup>14</sup>C) dates from Bird et al.[@main-ref-24] to construct SPDs, which serve as validated proxies for regional human population changes[@main-ref-26]. To associate radiocarbon dates with pollen sequences, a specific radius around each pollen sequence was defined. The default radius was set at 250 km to capture a reasonable density of <sup>14</sup>C dates, with the radius increased to 500 km for sites with insufficient coverage. This approach assumes that human populations were present and potentially influencing the region within these distances

Radiocarbon dates were carefully filtered for validity, ensuring accurate geographical location (longitude and latitude), and 'LocAccuracy' \> 0. These refined <sup>14</sup>C dates were calibrated using the “*calibrate()*” function from the *rcarbon* package[@methods-ref-72]. Appropriate calibration curves (“IntCal20”, “ShCal20”, “mixed”[@methods-ref-73; @methods-ref-74]) were applied, with the mixed curve generated using the “*rcarbon::mixCurves()*” function, setting p = 0.5. Calibration curve assignment was based on geographical location, following Hua et al.[@methods-ref-75]. The estimation of SPD was performed using the “*spd()*” function from the *rcarbon* package ranging from present to 12 ka BP. Sequences with fewer than 50 radiocarbon dates were excluded to maintain robust SPD estimates. We used a moving window of 100 years to smooth the non-normal peaks.

The number of <sup>14</sup>C dates decreases strongly toward younger material, particularly over the last 2 ka BP in Eurasia[@main-ref-24]. Therefore, we focused on the time-period between 8.5 and 2 ka BP, ensuring sufficient radiocarbon data and reliable SPD reconstruction. SPD values were extracted at every 500-year interval, providing a time-resolved predictor of past humans representing the magnitude of regional changes in human populations in different regions.

### Human events derived from fossil pollen sequences

We employed expert-based approach to detect periods of human activity in each pollen sequence. This binary approach identified “human events” based on anthropogenic indicator taxa, allowing us to integrate supplementary predictors of human presence and activity.

### Detection of human events in North America, Europe, Asia, and Oceania

For these regions, human events were identified through examination of each pollen diagram sequence by one or more regional specialists, who recorded the age of specific events (i.e., changes in anthropogenic indicator taxa). Event types were regional-specific and may have different interpretations even if the taxon involved is distributed across continents (see @exttbl-human-events). A binary matrix (0/1) was created for each event type detected in each pollen diagram sequence, incorporating the average ages between levels (samples), considering that human impact may have occurred in the intervals between samples in the fossil pollen sequences. Binary values (0/1) were assigned to different event types based on their presence (i.e., detection and the event's age). This assignment adhered to logical principles, and binary values were adjusted to compile event data for each pollen sequence. This results in a binary matrix of ages and event types for each sequence.

Note that the absence of human events in a pollen diagram sequence does not necessarily imply the absence of humans but rather indicates insufficient evidence to confirm human activity as detected in the pollen sequence.

### Detection of human events in Central and South America

Due to the complex and unique use of plants in Central and South America, we performed a thorough literature review targeting pollen types associated with human presence and/or activity[@main-ref-48]:

1.  Anthropogenic pollen indicators were identified from the literature as single human indicators or combined variations in a group of indicators (i.e. “human indices”).

2.  For each pollen sequence, the combinations of taxa recorded alongside specific indicator groups was considered. We evaluated whether the signal of a pollen indicator for human presence was weak or strong, applying a defined threshold.

3.  Two categories were established: “human-event indicators”, representing a single taxon associated with human activity categorised as having “weak” or “strong” impact; and “human-event indices”, comprising combinations of taxa classified similarly.

4.  For each pollen sequence, the human-event indicators and human-event indices were assessed for their presence at each level, with classification as "no impact", "weak impact" or "strong impact". Specifically, the presence of a single pollen grain of a human indicator signified “weak” impact, while the presence of more than one pollen grain of a strong impact indicator denoted “strong” impact. Additionally, the pollen type *Pinus* was considered a human indicator outside its native distribution, and for human-event indices (step 3), any quantity of pollen grains had to be present for the specific combination of taxa to be classified.

## Palaeoclimate

Palaeoclimate from the CHELSA-TraCE21k downscaling algorithm was downloaded from the CHELSA database which is based on the Community Climate System Model version 3[@main-ref-27]. The selected bioclimatic variables are *bio1*: annual mean temperature (℃), *bio6*: minimum temperature of the coldest month (℃), *bio18*: precipitation of warmest quarter (kg m<sup>-2</sup> quarter<sup>-1</sup>, = mm), and *bio19*: precipitation of coldest quarter (kg m<sup>-2</sup> quarter<sup>-1</sup>, = mm). The variables were selected *a priori* to represent subcontinental climate variability with respect to differences in temperature, moisture, or seasonality between the continental regions. The climate values were extracted for the co-ordinates for each *dataset_id* (pollen sequence) to retrieve the full time series for every 100 years for each climate variable. The point-based extraction of co-ordinates may provide a mismatch in elevation in areas with rough terrain. However, we assume the regional extent of the pollen signal is fairly comparable to the relevant spatial area of the climate signal per 1km spatial grid.

## Numerical analysis of hypothesis 1

To calculate the relative importance of human events and climate for variability in PAPs, we used hierarchical variation partitioning (HVARPART) developed by Lai et al.[@main-ref-28]. This approach calculates the importance of each predictor by partitioning the unique and shared variation for all possible combinations of predictor orders in a full model. The predictor importance is then the sum of the average unique and shared variation[@main-ref-28]. To obtain an estimate of predictor importance, we used redundancy analysis (RDA) with standardised response variables as pollen assemblage properties are of mixed units. Past humans (e.g. SPD values) represent one predictor, whereas climate is represented as a group of selected variables of summer precipitation, winter precipitation, annual temperature, and winter temperature. We used the adjusted *r*<sup>2</sup> total predictor importance and the average unique partitions as they correct for the number of samples and predictors in the model. To compare the predictor importance of humans and climate, we estimated the individual importance ratios for each sequence as follows:

*Predictor importance ratio* = *predictor importance* / (*predictor importance human* + *predictor importance climate*)

The analysis was run in two ways:

e.  to analyse the *spatial changes*, HVARPART was run for individual sequences. To summarise the results on broader scales within the continents, we used the Köppen-Geiger climate zones to categorise subregions and calculated the weighted mean ratios of the total predictor importance from each sequence using the sum of the predictor importance of humans and palaeoclimate as weights.

f.  to analyse the *temporal patterns* for each continent, HVARPART was run for samples within each 500-year time slice. Time slices with fewer than five samples were excluded, and some analyses failed when SPDs indicated zero human presence. Missing results in these cases were attributed to insufficient predictors. The predictor groups in each time slice consist of the SPD or group of human-detection events (@exttbl-human-events) together with the matrix of palaeoclimatic variables.

HVARPART analyses were run using the *rdacca.hp* R package [@main-ref-28]. Two site-based examples to analyse spatial changes are provided in @extfig-site-examples.

### Numerical analysis of hypothesis 2

To test if the interrelationships between PAPs have changed over time (H2), we performed a principal component analysis (PCA) with standardisation of the metrics within each 500-year time slice. Here samples were grouped at the subregional levels of climate zones within each continent. We performed a Procrustes sum-of-squares analysis to compare the changes in the interrelationships between PAPs between time slices[@main-ref-29]. We used symmetric scaling (*m*<sup>2</sup>) creating distance matrices representing these changes, where 0 indicates the relationship remained constant, and 1 indicates that the relationship between one or several PAPs has changed considerably. Each climate zone is represented by the *m*<sup>2</sup>-distances between time slices for the period 8.5–2 ka BP. This was used as a response matrix in HVARPART.

Bayesian modelling was employed to establish overarching trends in past humans (SPD) and palaeoclimate[@main-ref-30]. It is important to note that the predictions generated by these models encapsulate the prevailing trends in past human presence and palaeoclimate as relevant to the distribution of our compiled sequences and these patterns may not directly represent the broader historical human presence and palaeoclimate conditions in various climate zones; see [@extfig-spd-trajectories; @extfig-annual-temperature; @extfig-coldest-month-temperature; @extfig-warmest-quarter-precipitation; @extfig-coldest-quarter-precipitation]. Subsequently, these variables were employed as predictors in the second HVARPART, aimed at quantifying the importance of past human or palaeoclimate to the variability in the interrelationships between PAPs within climate zones. The general trends were also modelled for the human-impact events in different climate zones across the continental regions (@extfig-human-events).
