project:
  type: default
  output-dir: rendered
  render:
    - manuscript.qmd

format:
  pdf:
    documentclass: scrartcl
    pdf-engine: xelatex
    papersize: a4
    fontsize: 12pt
    geometry:
      - top=25mm
      - bottom=25mm
      - left=25mm
      - right=25mm
    linestretch: 1.5
    colorlinks: false
    fig-pos: H
    tbl-cap-location: top
    include-in-header: styles/submission.tex
  docx:
    reference-doc: reference/submitted-style-reference.docx
    toc: false
    number-sections: false
    fig-width: 6.3
    fig-height: 4.6
    tbl-cap-location: top

bibliography:
  - references/main-references.bib
  - references/methods-references.bib
csl: references/submitted-numeric.csl
citeproc: false
filters:
  - filters/split-bibliography.lua
link-citations: false
crossref:
  fig-title: Fig.
  fig-prefix: Fig.
  tbl-title: Table
  tbl-prefix: Table
  custom:
    - kind: float
      key: extfig
      latex-env: extfigure
      reference-prefix: Extended Fig.
      caption-prefix: Extended Fig.
    - kind: float
      key: exttbl
      latex-env: exttable
      caption-location: top
      reference-prefix: Extended Table
      caption-prefix: Extended Table

