# This file is generated from `package_list` in `R/00_Config_file.R`.
# Do not edit it manually.
# Literal library calls let renv discover dynamically loaded packages.
if (
  FALSE
) {
  library(assertthat)
  library(brms)
  library(collinear)
  library(colorspace)
  library(furrr)
  library(future)
  library(geosphere)
  library(ggeffects)
  library(ggpubr)
  library(here)
  library(httpgd)
  library(insight)
  library(janitor)
  library(jsonlite)
  library(knitr)
  library(languageserver)
  library(parallelly)
  library(rcarbon)
  library(rdacca.hp)
  library(dplyr)
  library(magrittr)
  library(maps)
  library(purrr)
  library(readr)
  library(REcopol)
  library(renv)
  library(remotes)
  library(rlang)
  library(RRatepol)
  library(RUtilpol)
  library(stringr)
  library(targets)
  library(terra)
  library(tibble)
  library(tidyr)
  library(tidyverse)
  library(usethis)
  library(utils)
  library(vegan)
  library(waffle)
  library(yaml)
}
